CREATE TABLE USER (
 Username VARCHAR(100) NOT NULL,
 Password VARCHAR(100) NOT NULL,
 Email VARCHAR(100) NOT NULL UNIQUE,
 FirstName VARCHAR(100) NOT NULL,
 LastName VARCHAR(100) NOT NULL,
 IsWorker BOOLEAN NOT NULL,
 isManager BOOLEAN NOT NULL,
 Address VARCHAR(100),
 City VARCHAR(100),
 State VARCHAR(100),
 Zip VARCHAR(100),
 PhoneNumber VARCHAR(100),
 Month VARCHAR(100),
 Day VARCHAR(100),
 Year VARCHAR(100),
 Gender BOOLEAN,
 PRIMARY KEY (Username) ) ENGINE=InnoDB;

CREATE TABLE SourceReport (
 Number INT NOT NULL,
 FullDate DATE NOT NULL,
 Reporter VARCHAR(100) NOT NULL,
 WaterType VARCHAR(100) NOT NULL,
 WaterCondition VARCHAR(100) NOT NULL,
 Location VARCHAR(250) NOT NULL,
 Latitude DOUBLE NOT NULL,
 Longitude DOUBLE NOT NULL,
 PRIMARY KEY (Number) ) ENGINE=InnoDB;

CREATE TABLE QualityReport (
Number INT NOT NULL,
FullDate DATE NOT NULL,
Reporter VARCHAR(100) NOT NULL,
WaterCondition VARCHAR(100) NOT NULL,
VirusPPM DOUBLE NOT NULL,
ContaminantPPM DOUBLE NOT NULL,
Location VARCHAR(250) NOT NULL,
Latitude DOUBLE NOT NULL,
Longitude DOUBLE NOT NULL,
PRIMARY KEY (Number) ) ENGINE=InnoDB;

